object Versions {
    const val kotlin = "1.6.10"
    const val compose = "1.2.0-alpha03"
    const val material3 = "1.0.0-alpha02"
    const val androidX = "1.1.1"
    const val hilt = "2.42"
    const val composeNavigationVersion = "2.4.0-alpha06"
    const val accompanist = "0.20.3"
    const val workVersion = "2.7.1"
    const val condtraint = "1.0.0-beta02"
    const val retrofitVersion = "2.6.0"
    const val retrofitConvVersion = "2.2.0"
    const val retrofitLoggerVersion = "3.4.1"
    const val kotlinCoroutinesAndroidVersion = "1.4.2"
    const val kotlinCoroutinesCore = "1.6.1"
    const val viewModelKtxVersion = "2.3.1"
    const val kotlinCoroutines = "1.6.4"
    const val pagingVersion = "3.0.1"
    const val room = "2.4.2"
    const val plugin_serialization = "1.6.21"
}
